apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    app: redis-commander
    heritage: harpoon
    name: redis-commander
    vender: qingyuanos.io
spec:
  type: NodePort
  ports:
  - name: redisadmwui
    nodePort: 32122
    port: 8081
    protocol: TCP
  selector:
    name: redis-commander
